Insert into MA_STUDENT.CUSTOMERS (CUST_NUM, COMPANY, CREDIT_LIMIT)
values ('1111', 'COMPANY1', '10000');
Insert into MA_STUDENT.CUSTOMERS (CUST_NUM, COMPANY, CREDIT_LIMIT)
values ('2222', 'COMPANY2', '20000');